/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.CivitasJuego;
import civitas.Diario;
import civitas.Jugador;
import civitas.OperacionesJuego;
import civitas.SalidasCarcel;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Padial
 */
public class CivitasView extends javax.swing.JFrame {

    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        jugadorPanel = new JugadorPanel();
        vistaCasilla = new CasillaPanel();
        contenedorVistaJugador.add(jugadorPanel);
        contenedorVistaCasilla.add(vistaCasilla);
        labelRanking.setVisible(false);
        muestraRanking.setVisible(false);
        gestionador = new GestionarDialog(this,true);
        diarioD = new DiarioDialog(this,true);
        
        repaint();
        revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        CivitasJuego = new javax.swing.JLabel();
        contenedorVistaJugador = new javax.swing.JPanel();
        contenedorVistaCasilla = new javax.swing.JPanel();
        labelOper = new javax.swing.JLabel();
        sigOper = new javax.swing.JTextField();
        labelRanking = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        muestraRanking = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CivitasJuego.setText("CivitasJuego");
        CivitasJuego.setEnabled(false);

        contenedorVistaJugador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        contenedorVistaCasilla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelOper.setText("Sig. Operacion");

        sigOper.setBackground(new java.awt.Color(255, 255, 204));
        sigOper.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sigOper.setEnabled(false);

        labelRanking.setText("Ranking");

        muestraRanking.setBackground(new java.awt.Color(255, 153, 153));
        muestraRanking.setColumns(20);
        muestraRanking.setRows(5);
        muestraRanking.setBorder(null);
        jScrollPane1.setViewportView(muestraRanking);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("Muestra Eventos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(CivitasJuego)
                        .addGap(74, 74, 74)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelOper)
                        .addGap(18, 18, 18)
                        .addComponent(sigOper, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                    .addComponent(contenedorVistaCasilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRanking)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CivitasJuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelOper)
                            .addComponent(sigOper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(contenedorVistaCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(labelRanking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mostrarEventos();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CivitasJuego;
    private javax.swing.JPanel contenedorVistaCasilla;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelOper;
    private javax.swing.JLabel labelRanking;
    private javax.swing.JTextArea muestraRanking;
    private javax.swing.JTextField sigOper;
    // End of variables declaration//GEN-END:variables
    
    CivitasJuego juego;
    JugadorPanel jugadorPanel;
    CasillaPanel vistaCasilla; 
    GestionarDialog gestionador;
    DiarioDialog diarioD;
    
    public void mostrarSiguienteOperacion(OperacionesJuego oper){
        sigOper.setText(oper.toString());
        repaint();
    }
    
    public void setCivitasJuego(CivitasJuego jug){
        this.juego = jug;
        setVisible(true);
    }
    
    public void actualizarVista(){
        jugadorPanel.setJugador(juego.getJugadorActual());
        vistaCasilla.setCasilla(juego.getCasillaActual());
        mostrarSiguienteOperacion(juego.getSiguienteOperacion());
        
        if(juego.finalDelJuego()){
            labelRanking.setVisible(true);
            muestraRanking.setVisible(true);
            String infoRanking = juego.ranking().toString();
            muestraRanking.setText(infoRanking);
            repaint();
            revalidate();
        }
        
        repaint();
        revalidate();
    }
    
    void mostrarEventos(){
        if(Diario.getInstance().eventosPendientes()){
            diarioD.mostrarEventos();
            diarioD.setVisible(true);   
        }
    }
    
    Respuestas comprar(){
        int opcion = JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?","Compra", JOptionPane.YES_NO_OPTION);
        
        if(opcion == 0){
            return Respuestas.SI;
        }else{
            return Respuestas.NO;
        }
    }
    
    public void gestionar(){
        gestionador.gestionar(juego.getJugadorActual());
        gestionador.pack();
        gestionador.repaint();
        gestionador.revalidate();
        gestionador.setVisible(true);
    }
    
    public int getGestion(){
        return gestionador.getGestion();
    }
    
    public int getPropiedad(){
        return gestionador.getPropiedad();
    }
    
    public SalidasCarcel salirCarcel(){
        String[] opciones = {"TIRANDO", "PAGANDO"};
        int respuesta = JOptionPane.showOptionDialog(null, "¿Cómo quieres salir de la cárcel?","Salir de la cárcel", JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null, opciones, opciones[0]);
    
        if(respuesta == 0){
            return SalidasCarcel.TIRANDO;
        }
        else{
            return SalidasCarcel.PAGANDO;
        }
    }
    
}

